# Build and Run Code Coverage on Main 

name: .NET Build and Coverage

on:
  workflow_run:
    workflows: ["render-md-mermaid"]
    types:
      - completed

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test 
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../.coverage/lcov
      
      - name: Upload new code coverage
        uses: actions/upload-artifact@v2
        with:
          name: lcov.info
          path: ./Test/.coverage/lcov.info
  
  base_branch_cov:
    needs: build_and_test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x 

      - name: Base Coverage 
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../.coverage/base_lcov

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v2
        with:
          name: base_lcov.info
          path: ./Test/.coverage/base_lcov.info

  checks:
    runs-on: ubuntu-latest
    needs: base_branch_cov

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.11.0
        uses: actions/setup-node@v1
        with:
          node-version: v16.11.0

      - name: Download code coverage report from base branch
        uses: actions/download-artifact@v2
        with:
          name: base_lcov.info

      - name: Download code coverage report for incoming changes
        uses: actions/download-artifact@v2
        with:
          name: lcov.info

      - name: Generate Code Coverage report 
        id: code-coverage
        uses: barecheck/code-coverage-action@v0.5.1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./lcov.info"
          base-lcov-file: "./base_lcov.info"
          minimum-ratio: 0 # Fails Github action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: "warning"